language: node_js

node_js:
  - 'node'
  - '8'
  - '6'
  - '4'
  - 'iojs'
  - '0.12'

script:
  - npm test

#addons:
#  code_climate:
#    repo_token: 08120a5f6442a389a93094fd9f5f25099e912f4807936ff46f85234037ca9585
#
#after_script:
#  - npm run coverage
#  - codeclimate-test-reporter < coverage/lcov.info

jobs:
  include:
    - stage: npm release
      node_js: '6'
      script: echo "Deploying to npm ..."
      after_script: skip
      deploy:
        provider: npm
        email: vatev.1+npm@gmail.com
        api_key:
          secure: au15nS6dstyZibmotHJ4DX2NnYTzYLWOOf73VzvO1Hv2ybxLCNAUKezPJBLDk+g1975ExD77v5fZbvnwyuFIOZfkMYzu4hOwwhFDhJu9EQQ5BWuGhUQafPD8ualErjk/poBQSCAP/XMBvfHNwWJyRPvH+8hXs8WdOkD1V8G69t/BiSDtyXfg1haSZrZlkJyE/+meQHymRIglfwdcSxvsWhrLc6Oad5SoeoL7xyu/BOmNUoCs0wg80rZKp1rRER0EgZrDRL1cp4Vroh3fTQfBm/2ruer3Xw7y8vQezbbjGpeZW92aoGMH3Pprpb0Dtcif/YSseHg2zdzLElV99/8V35YpIHsyKmY5k8NUZyxLGGsHNTTwW+hb5VbBCrI2KCbNGez6l+5A/61OOGnJn5AAvlKHgoBNX8HjAiFJFoVEKdltRVBldRL2eqnC0pQc2Xjcr4Da/9hSgD0LT2EAfCHeQozKrFH28KLatSyqhFYfS7vs4SaBpyiumLBlB0b08OP0og5kXjtyOCEuM9/qUpDHfF+8mH9QmYYykE8q6aRwtPG89gbztZimkdEx8AvxzYPyWhi+PsJzQSiZHL4QP23DG/pFS7/0scN3ty5tmJZrG/pc8ZpnyK2mYVplMfjMgUdMwIqslSnQeZNt8InM1adK14PyBTOE/rpXOmo+URQMvOs=
        on:
          tags: true
          repo: catdad/mocha-script-reporter
